name: CI_CD
 
on: 
    push:
        branches: 
            - main
            - dev
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: testing
          run: |
            python Test_speed_3.py
            python Test_functions.py
            python Test_exception.py
